backend:
  name: github
  repo: lepetitforgeron/lepetitforgeron

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: complex
    label: Complex
    folder: src/cmplx
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - name: "listtest"
        label: "List Test"
        widget: "list"
        allow_add: true
        fields: 
          - { name: name, label: Name }
          - { name: other, label: other}
        
